### ISSUE TITLE
Docker: OTOBO image can't be built with DBD::mysql 5.001

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#2548]
A new version of DBD::mysql. mariadb-client-10.3, has landed today. I assume that this is the reason why building the Docker image for rel-10_0 fails. The build fails both locally and on hub.docker.com.

The [change log for DBD::mysql 5.001](https://metacpan.org/release/DVEEDEN/DBD-mysql-5.001/source/Changes) states:

> Only support MySQL 8.x as MySQL 5.7 is going EOL soon

This is related to end of life for MySQL 5.7: https://www.pathinfotech.com/mysql-5-7-support-ends-soon-upgrade-to-mysql-8-0-today/

The Docker image is based on Debian 10 Buster, which supplies [mariadb-client-10.3](https://packages.debian.org/buster/mariadb-client-10.3) as the default mysql client. It is not obvious whether that version falls under "MySQL 5.7" support.

Installing DBD::mysql 5.001 manually in the relevant environment seem to be in line with the changes for DBD::mysql 5.001.
The relevant commit seems to be: https://github.com/perl5-dbi/DBD-mysql/commit/9076a7f75cc9fee09ecc90340772fe544eaf1531

> "/usr/local/bin/perl" -MExtUtils::Command::MM -e 'cp_nonempty' -- mysql.bs blib/arch/auto/DBD/mysql/mysql.bs 644 
> cc -c  -I/opt/otobo_install/local/lib/perl5/x86_64-linux-gnu/auto/DBI -I/usr/include/mariadb -I/usr/include/mariadb/mysql -g  -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2 -O2   -DVERSION=\"5.001\" -DXS_VERSION=\"5.001\" -fPIC "-I/usr/local/lib/perl5/5.32.1/x86_64-linux-gnu/CORE"   dbdimp.c
> dbdimp.c: In function ‘mysql_dr_connect’:
> dbdimp.c:1407:31: error: ‘MYSQL_OPT_GET_SERVER_PUBLIC_KEY’ undeclared (first use in this function); did you mean ‘MYSQL_SERVER_PUBLIC_KEY’?
>            mysql_options(sock, MYSQL_OPT_GET_SERVER_PUBLIC_KEY, &server_get_pubkey);
>                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>                                MYSQL_SERVER_PUBLIC_KEY
> dbdimp.c:1407:31: note: each undeclared identifier is reported only once for each function it appears in
> dbdimp.c:1464:22: error: ‘SSL_MODE_PREFERRED’ undeclared (first use in this function); did you mean ‘SO_PEERCRED’?
>            ssl_mode = SSL_MODE_PREFERRED;
>                       ^~~~~~~~~~~~~~~~~~
>                       SO_PEERCRED
> dbdimp.c:1466:19: error: ‘SSL_MODE_VERIFY_IDENTITY’ undeclared (first use in this function)
>         ssl_mode = SSL_MODE_VERIFY_IDENTITY;
>                    ^~~~~~~~~~~~~~~~~~~~~~~~
> dbdimp.c:1468:19: error: ‘SSL_MODE_VERIFY_CA’ undeclared (first use in this function)
>         ssl_mode = SSL_MODE_VERIFY_CA;
>                    ^~~~~~~~~~~~~~~~~~
> dbdimp.c:1470:19: error: ‘SSL_MODE_REQUIRED’ undeclared (first use in this function); did you mean ‘OP_REQUIRE’?
>         ssl_mode = SSL_MODE_REQUIRED;
>                    ^~~~~~~~~~~~~~~~~
>                    OP_REQUIRE
> dbdimp.c:1471:30: error: ‘MYSQL_OPT_SSL_MODE’ undeclared (first use in this function); did you mean ‘MYSQL_OPT_SSL_CRL’?
>       if (mysql_options(sock, MYSQL_OPT_SSL_MODE, &ssl_mode) != 0) {
>                               ^~~~~~~~~~~~~~~~~~
>                               MYSQL_OPT_SSL_CRL
> ...
>

**Comment by bschmalhofer** [comment]
I think that for 10.0.19 there is no need to make large changes. Simply require that for Docker builds the version of DBD::mysql is below 5.001.
Switching to DBD::MariaDB is not a good option, see #1860.

**Comment by bschmalhofer** [comment]
I had the wrong impression that DBD::mysql could be compiled on Debian 12 Bookworm. This would be the relevant version for rel-10_1 and rel-11_0. So I expect that this will be fixed in DBD::mysql.  In the meantime the version 5.001 can be put on the blacklist.

Note that this affects all types of installation. But I think that the number of systems that have DBD::mysql 5.001 already installed and want to install or upgrade OTOBO is fairly small.

**Comment by bschmalhofer** [comment]
Creating the Docker images works with the blacklisted DBD::mysl 5.001. Closing this issue.

**Comment by bschmalhofer** [comment]
I just encountered a failure of the Docker build as DBD:;mysql 5.003 could not be built. This leads to the conclusion that not only DBD::mysql 5.001 should be blacklisted, but all versions  > 5.001.
